FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Copy the compiled JAR file generated by GitHub Actions
COPY target/*.jar app.jar

# Expose the standard Spring Boot port
EXPOSE 8080

# Run the application with a 300MB memory limit
ENTRYPOINT ["java", "-Xmx300m", "-jar", "app.jar"]